package Main.Java.saud.sparqlLogging.model;

/**
 * User: Saud Aljaloud email: sza1g10@ecs.soton.ac.uk
 */

public class Prefixes {

	static String prefixes = "PREFIX a:	<http://www.w3.org/2005/Atom>\n"
			+ "PREFIX address:	<http://schemas.talis.com/2005/address/schema#>\n"
			+ "PREFIX admin:	<http://webns.net/mvcb/>\n"
			+ "PREFIX atom:	<http://atomowl.org/ontologies/atomrdf#>\n"
			+ "PREFIX aws:	<http://soap.amazon.com/>\n"
			+ "PREFIX b3s:    <http://b3s.openlinksw.com/>\n"
			+ "PREFIX batch:	<http://schemas.google.com/gdata/batch>\n"
			+ "PREFIX bibo:	<http://purl.org/ontology/bibo/>\n"
			+ "PREFIX bif:	<>\n"
			+ "PREFIX bugzilla:	<http://www.openlinksw.com/schemas/bugzilla#>\n"
			+ "PREFIX c:	<http://www.w3.org/2002/12/cal/icaltzd#>\n"
			+ "PREFIX category:	<http://dbpedia.org/resource/Category:>\n"
			+ "PREFIX cb:	<http://www.crunchbase.com/>\n"
			+ "PREFIX cc:	<http://web.resource.org/cc/>\n"
			+ "PREFIX content:	<http://purl.org/rss/1.0/modules/content/>\n"
			+ "PREFIX cv:	<http://purl.org/captsolo/resume-rdf/0.2/cv#>\n"
			+ "PREFIX cvbase:	<http://purl.org/captsolo/resume-rdf/0.2/base#>\n"
			+ "PREFIX dawgt:	<http://www.w3.org/2001/sw/DataAccess/tests/test-dawg#>\n"
			+ "PREFIX dbpedia:	<http://dbpedia.org/resource/>\n"
			+ "PREFIX dbpedia-owl:	<http://dbpedia.org/ontology/>\n"
			+ "PREFIX dbpprop:	<http://dbpedia.org/property/>\n"
			+ "PREFIX dc:	<http://purl.org/dc/elements/1.1/>\n"
			+ "PREFIX dcterms:	<http://purl.org/dc/terms/>\n"
			+ "PREFIX digg:	<http://digg.com/docs/diggrss/>\n"
			+ "PREFIX ebay:	<urn:ebay:apis:eBLBaseComponents>\n"
			+ "PREFIX enc:	<http://purl.oclc.org/net/rss_2.0/enc#>\n"
			+ "PREFIX exif:	<http://www.w3.org/2003/12/exif/ns/>\n"
			+ "PREFIX fb:	<http://api.facebook.com/1.0/>\n"
			+ "PREFIX ff:	<http://api.friendfeed.com/2008/03>\n"
			+ "PREFIX fn:	<http://www.w3.org/2005/xpath-functions/#>\n"
			+ "PREFIX foaf:	<http://xmlns.com/foaf/0.1/>\n"
			+ "PREFIX freebase:	<http://rdf.freebase.com/ns/>\n"
			+ "PREFIX g:	<http://base.google.com/ns/1.0>\n"
			+ "PREFIX gb:	<http://www.openlinksw.com/schemas/google-base#>\n"
			+ "PREFIX gd:	<http://schemas.google.com/g/2005>\n"
			+ "PREFIX geo:	<http://www.w3.org/2003/01/geo/wgs84_pos#>\n"
			+ "PREFIX geonames:	<http://www.geonames.org/ontology#>\n"
			+ "PREFIX georss:	<http://www.georss.org/georss>\n"
			+ "PREFIX gml:	<http://www.opengis.net/gml>\n"
			+ "PREFIX go:	<http://purl.org/obo/owl/GO#>\n"
			+ "PREFIX gr:	<http://purl.org/goodrelations/v1#>\n"
			+ "PREFIX grs:	<http://www.georss.org/georss/>\n"
			+ "PREFIX hlisting:	<http://www.openlinksw.com/schemas/hlisting/>\n"
			+ "PREFIX hoovers:	<http://wwww.hoovers.com/>\n"
			+
			// "PREFIX hrev:	<http:/www.purl.org/stuff/hrev#>\n" +
			"PREFIX ical:	<http://www.w3.org/2002/12/cal/ical#>\n"
			+ "PREFIX ir:	<http://web-semantics.org/ns/image-regions>\n"
			+ "PREFIX itunes:	<http://www.itunes.com/DTDs/Podcast-1.0.dtd>\n"
			+ "PREFIX lgv:	<http://linkedgeodata.org/ontology/>\n"
			+ "PREFIX link:	<http://www.xbrl.org/2003/linkbase>\n"
			+ "PREFIX lod:	<http://lod.openlinksw.com/>\n"
			+ "PREFIX math:	<http://www.w3.org/2000/10/swap/math#>\n"
			+ "PREFIX media:	<http://search.yahoo.com/mrss/>\n"
			+ "PREFIX mesh:	<http://purl.org/commons/record/mesh/>\n"
			+ "PREFIX meta:	<urn:oasis:names:tc:opendocument:xmlns:meta:1.0>\n"
			+ "PREFIX mf:	<http://www.w3.org/2001/sw/DataAccess/tests/test-manifest#>\n"
			+ "PREFIX mmd:	<http://musicbrainz.org/ns/mmd-1.0#>\n"
			+ "PREFIX mo:	<http://purl.org/ontology/mo/>\n"
			+ "PREFIX mql:	<http://www.freebase.com/>\n"
			+ "PREFIX nci:	<http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#>\n"
			+ "PREFIX nfo:	<http://www.semanticdesktop.org/ontologies/nfo/#>\n"
			+ "PREFIX ng:	<http://www.openlinksw.com/schemas/ning#>\n"
			+ "PREFIX nyt:	<http://www.nytimes.com/>\n"
			+ "PREFIX oai:	<http://www.openarchives.org/OAI/2.0/>\n"
			+ "PREFIX oai_dc:	<http://www.openarchives.org/OAI/2.0/oai_dc/>\n"
			+ "PREFIX obo:	<http://www.geneontology.org/formats/oboInOwl#>\n"
			+ "PREFIX office:	<urn:oasis:names:tc:opendocument:xmlns:office:1.0>\n"
			+ "PREFIX oo:	<urn:oasis:names:tc:opendocument:xmlns:meta:1.0:>\n"
			+ "PREFIX openSearch:	<http://a9.com/-/spec/opensearchrss/1.0/>\n"
			+ "PREFIX opencyc:	<http://sw.opencyc.org/2008/06/10/concept/>\n"
			+ "PREFIX opl:	<http://www.openlinksw.com/schema/attribution#>\n"
			+ "PREFIX opl-gs:	<http://www.openlinksw.com/schemas/getsatisfaction/>\n"
			+ "PREFIX opl-meetup:	<http://www.openlinksw.com/schemas/meetup/>\n"
			+ "PREFIX opl-xbrl:	<http://www.openlinksw.com/schemas/xbrl/>\n"
			+ "PREFIX oplweb:	<http://www.openlinksw.com/schemas/oplweb#>\n"
			+ "PREFIX ore:	<http://www.openarchives.org/ore/terms/>\n"
			+ "PREFIX owl:	<http://www.w3.org/2002/07/owl#>\n"
			+ "PREFIX product:	<http://www.buy.com/rss/module/productV2/>\n"
			+ "PREFIX protseq:	<http://purl.org/science/protein/bysequence/>\n"
			+ "PREFIX r:	<http://backend.userland.com/rss2>\n"
			+ "PREFIX radio:	<http://www.radiopop.co.uk/>\n"
			+ "PREFIX rdf:	<http://www.w3.org/1999/02/22-rdf-syntax-ns#>\n"
			+ "PREFIX rdfa:	<http://www.w3.org/ns/rdfa#>\n"
			+ "PREFIX rdfdf:	<http://www.openlinksw.com/virtrdf-data-formats#>\n"
			+ "PREFIX rdfs:	<http://www.w3.org/2000/01/rdf-schema#>\n"
			+
			// "PREFIX rev:	<http://purl.org/stuff/rev#>\n" +
			// "PREFIX review:	<http:/www.purl.org/stuff/rev#>\n" +
			"PREFIX rss:	<http://purl.org/rss/1.0/>\n"
			+ "PREFIX sc:	<http://purl.org/science/owl/sciencecommons/>\n"
			+ "PREFIX scovo:	<http://purl.org/NET/scovo#>\n"
			+ "PREFIX sd:	<http://www.w3.org/ns/sparql-service-description#>\n"
			+ "PREFIX sf:	<urn:sobject.enterprise.soap.sforce.com>\n"
			+ "PREFIX sioc:	<http://rdfs.org/sioc/ns#>\n"
			+ "PREFIX sioct:	<http://rdfs.org/sioc/types#>\n"
			+ "PREFIX skos:	<http://www.w3.org/2004/02/skos/core#>\n"
			+ "PREFIX slash:	<http://purl.org/rss/1.0/modules/slash/>\n"
			+ "PREFIX sql:	<>\n"
			+ "PREFIX stock:	<http://xbrlontology.com/ontology/finance/stock_market#>\n"
			+ "PREFIX twfy:	<http://www.openlinksw.com/schemas/twfy#>\n"
			+ "PREFIX umbel:	<http://umbel.org/umbel#>\n"
			+ "PREFIX umbel-ac:	<http://umbel.org/umbel/ac/>\n"
			+ "PREFIX umbel-sc:	<http://umbel.org/umbel/sc/>\n"
			+ "PREFIX uniprot:	<http://purl.uniprot.org/>\n"
			+ "PREFIX units:	<http://dbpedia.org/units/>\n"
			+ "PREFIX usc:	<http://www.rdfabout.com/rdf/schema/uscensus/details/100pct/>\n"
			+ "PREFIX v:	<http://www.openlinksw.com/xsltext/>\n"
			+ "PREFIX vcard:	<http://www.w3.org/2001/vcard-rdf/3.0#>\n"
			+ "PREFIX vcard2006:	<http://www.w3.org/2006/vcard/ns#>\n"
			+ "PREFIX vi:	<http://www.openlinksw.com/virtuoso/xslt/>\n"
			+ "PREFIX virt:	<http://www.openlinksw.com/virtuoso/xslt>\n"
			+ "PREFIX virtcxml:	<http://www.openlinksw.com/schemas/virtcxml#>\n"
			+ "PREFIX virtrdf:	<http://www.openlinksw.com/schemas/virtrdf#>\n"
			+ "PREFIX void:	<http://rdfs.org/ns/void#>\n"
			+ "PREFIX wb:	<http://www.worldbank.org/>\n"
			+ "PREFIX wdrs:	<http://www.w3.org/2007/05/powder-s#>\n"
			+ "PREFIX wf:	<http://www.w3.org/2005/01/wf/flow#>\n"
			+ "PREFIX wfw:	<http://wellformedweb.org/CommentAPI/>\n"
			+ "PREFIX wikicompany:	<http://dbpedia.openlinksw.com/wikicompany/>\n"
			+ "PREFIX xf:	<http://www.w3.org/2004/07/xpath-functions>\n"
			+ "PREFIX xfn:	<http://gmpg.org/xfn/11#>\n"
			+ "PREFIX xhtml:	<http://www.w3.org/1999/xhtml>\n"
			+ "PREFIX xhv:	<http://www.w3.org/1999/xhtml/vocab#>\n"
			+ "PREFIX xi:	<http://www.xbrl.org/2003/instance>\n"
			+ "PREFIX xml:	<http://www.w3.org/XML/1998/namespace>\n"
			+ "PREFIX xn:	<http://www.ning.com/atom/1.0>\n"
			+ "PREFIX xsd:	<http://www.w3.org/2001/XMLSchema#>\n"
			+ "PREFIX xsl10:	<http://www.w3.org/XSL/Transform/1.0>\n"
			+ "PREFIX xsl1999:	<http://www.w3.org/1999/XSL/Transform>\n"
			+ "PREFIX xslwd:	<http://www.w3.org/TR/WD-xsl>\n"
			+ "PREFIX y:	<urn:yahoo:maps>\n"
			+ "PREFIX yago:	<http://dbpedia.org/class/yago/>\n"
			+ "PREFIX yago-res:	<http://mpii.de/yago/resource/>\n"
			+ "PREFIX yt:	<http://gdata.youtube.com/schemas/2007>\n"
			+ "PREFIX zem:	<http://s.zemanta.com/ns#>\n" + "";

}
